### ISSUE TITLE
Grafen

### ISSUE THREAD

**Issue by alexv-ds** [Derven/derven_station#1]
Квадратный свет ныне морально устарел (нет ^^).  Новый бьенд позволяет сделать истинно кругленький свет не прилагая особых усилий.
[Тыц](http://www.byond.com/developer/Nadrew/LightingTest)

**Comment by Derven** [comment]
Но ведь это не олдскул. Да и особых усилий я пока тоже не прилагал.

**Comment by Derven** [comment]
Я думаю идеальным будет вариант, если будет возможность выбора света при запуске или отключив файл.
